# This file was generated by GoReleaser. DO NOT EDIT.
cask "hay" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "0f14791d41134490596da25d899088ccb1fd1795fb1c50feda126c05f1f52210"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "4a87c3d049562bd6a84f52bbab20fd0390579574973603aad76cfc670cbd0ad5"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "979df2bc5fe0f8718f83b15761148da4d6e7cccad649aafb22b5b8e34aeae00a"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9bdfaf87b993a6ef50e35ded3aa1a40f0bae790bfd50de71fc0776cbc9c7e37b"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hay"
  desc "Private search and Q&A for your documents. One binary, fully local."
  homepage "https://github.com/BenyD/haypile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hay"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hay"]
    end
  end

  # No zap stanza required

end
