# This file was generated by GoReleaser. DO NOT EDIT.
cask "hay" do
  version "0.2.4"

  on_macos do
    on_intel do
      sha256 "243c7cc9fc2d192a73ca8a841efb69221c06fc7dd12c0806a5302335ca4d742e"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d0e2bdf4a3d3608844212222c0e5eac43b0a57c2c9dfc1e440e86ca9ed6ae332"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb49f4592e689221c5c501f37bfe4d73e80b4286b545f299f973aaf315ed199e"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "131296ac2aaf7e6d2f38a74a60959a93a22126a5539d2f65a7a68f6b4ed62288"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hay"
  desc "Private search and Q&A for your documents. One binary, fully local."
  homepage "https://github.com/BenyD/haypile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hay"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hay"]
    end
  end

  # No zap stanza required

end
