# This file was generated by GoReleaser. DO NOT EDIT.
cask "hay" do
  version "0.2.2"

  on_macos do
    on_intel do
      sha256 "d0651eaec696bf682a22d15526a770add04178125cd668072aa2204e997cc0bd"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0559c9462b6f6480b7a51fc8013c762c7f8bc55908708604cecb11b6c7d467d9"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "babdf71a152d4c0c4a255a67cd7d87369f24be77311d92aad3a4bbbd6667a270"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d7e798597be4dd071bf57e11a6ceb3ef73a085bce3fef7464cb50451e1cd7be9"
      url "https://github.com/BenyD/haypile/releases/download/v#{version}/haypile_#{version}_linux_arm64.tar.gz"
    end
  end

  name "hay"
  desc "Private search and Q&A for your documents. One binary, fully local."
  homepage "https://github.com/BenyD/haypile"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "hay"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/hay"]
    end
  end

  # No zap stanza required

end
